
language: elixir

sudo: required

elixir:
  - 1.8.0
  - 1.8.1
  - 1.8.2
  - 1.9.0
  - 1.9.1
otp_release:
  - 21.0
  - 22.0

env:
  - MIX_ENV=test

matrix:
  include:
    # Elixir format
    - elixir: 1.9.1
      script:
        - mix format --check-formatted
    # Elixir credo
    - elixir: 1.9.1
      script:
        - mix credo --strict

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix compile
  - mix test
