
language: elixir

sudo: required

elixir:
  - 1.8.0
  - 1.8.1
  - 1.8.2
  - 1.9.0
  - 1.9.1
otp_release:
  - 21.0
  - 22.0

env:
  - MIX_ENV=test

addons:
  postgresql: "9.6"

services:
  - rabbitmq

matrix:
  include:
    # Elixir format
    - elixir: 1.9.1
      script:
        - mix format --check-formatted
      env: CHECK_FORMAT=TRUE
    # Elixir credo
    - elixir: 1.9.1
      script:
        - mix credo --strict
      env: CHECK_SYNTAX=TRUE
    # Elixir coveralls
    - elixir: 1.9.1
      script:
        - MIX_ENV=test mix coveralls.travis
      env: COVERALLS=TRUE

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

before_script:
  - mkdir -p priv/repo/migrations

script:
  - mix compile
  - mix test
