
language: elixir

sudo: required

elixir:
  - 1.8.0
  - 1.8.1
  - 1.8.2
  - 1.9.0
  - 1.9.1
otp_release:
  - 21.0
  - 22.0

env:
  - MIX_ENV=test

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - if [[ $(elixir --version) = *"1.9"* ]]; then mix format --check-formatted; fi
  - mix compile
  - mix test
